spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hiberate:
      ddl-auto: create
    properties:
      hiberate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibrate.SQL: debug

